version: "3.9"

services:
  app:
    build:
      args:
        user: matheusbrdev
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: local/php-8.1.7:1.0.1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: school-api-container
    ports:
      - "8000:80"
    restart: always
    working_dir: /var/www/html/school-app
    volumes:
      - ./school-app:/var/www/html/school-app
      - ./docker-compose/xdebug/99-xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
      - ./docker-compose/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    networks:
      - school-net

  db:
    image: mysql:5.7
    container_name: school-db
    restart: unless-stopped
    ports:
    - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - school-net

networks:
  school-net:
    driver: bridge